apiVersion : apps/v1
kind: Deployment
metadata:
  name: mondoo-app 
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: mondoo-app
  template:
    metadata:
      labels:
        app: mondoo-app 
    spec:
      containers:
        - name: mondoo-app 
          image: securityimages.azurecr.io/mondoo-app:latest
          ports:
          - containerPort: 80
